config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :beverages
  get 'welcome/index'

  root 'home#index'

end

app/models/beverage.rb
class Beverage < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/beverages_controller.rb
class BeveragesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_beverage, only: [:show, :edit, :update, :destroy]

  # GET /beverages
  # GET /beverages.json
  def index
    @beverages = Beverage.all
  end

  # GET /beverages/1
  # GET /beverages/1.json
  def show
  end

  # GET /beverages/new
  def new
    @beverage = Beverage.new
  end

  # GET /beverages/1/edit
  def edit
  end

  # POST /beverages
  # POST /beverages.json
  def create
    @beverage = Beverage.new(beverage_params)

    respond_to do |format|
      if @beverage.save
        format.html { redirect_to @beverage, notice: 'Your beverage was successfully created.' }
        format.json { render :show, status: :created, location: @beverage }
      else
        format.html { render :new }
        format.json { render json: @beverage.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /beverages/1
  # PATCH/PUT /beverages/1.json
  def update
    respond_to do |format|
      if @beverage.update(beverage_params)
        format.html { redirect_to @beverage, notice: 'Your beverage is updated.' }
        format.json { render :show, status: :ok, location: @beverage }
      else
        format.html { render :edit }
        format.json { render json: @beverage.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /beverages/1
  # DELETE /beverages/1.json
  def destroy
    @beverage.destroy
    respond_to do |format|
      format.html { redirect_to beverages_url, notice: 'Your beverage has been deleted.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_beverage
      @beverage = Beverage.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def beverage_params
      params.require(:beverage).permit(:name, :kind)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def index
		if user_signed_in?
			redirect_to beverages_path
		end
	end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/beverages_helper.rb
module BeveragesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/beverages/_form.html.erb
<%= form_for(@beverage) do |f| %>
  <% if @beverage.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@beverage.errors.count, "error") %> prohibited this beverage from being saved:</h2>

      <ul>
      <% @beverage.errors.full_messages.each do |message| %>
        <li class="alert-box warning round"><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :kind %><br>
    <%= f.text_field :kind %>
    
  </div>
  <div class="actions">
    <%= f.submit 'Save Your Beverage', :class => 'tiny button' %>

  </div>
<% end %>

app/views/beverages/edit.html.erb
<h1>Editing Beverage</h1>

<%= render 'form' %>

<%= link_to 'Show', @beverage %> |
<%= link_to 'Back', beverages_path %>

app/views/beverages/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Vote for Your Favorite Beverages!</h1>
<p>Review the list of beverages and use the up or down arrows to vote for your favorite beverages!</p>
<table class="responsive">
  <thead>
    <tr>
      <th width="200">Name</th>
      <th width="200">Kind</th>
      <th colspan="3">Controls</th>
    </tr>
  </thead>

  <tbody>
    <% @beverages.each do |beverage| %>
      <tr>
        <td><%= beverage.name %></td>
        <td><%= beverage.kind %></td>
        <td><%= link_to 'View', beverage %></td>
        <td><%= link_to 'Edit', edit_beverage_path(beverage) %></td>
        <td><%= link_to 'Delete', beverage, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<button type="button" class="tiny button"><%= link_to 'Add A Beverage', new_beverage_path %></button>

app/views/beverages/new.html.erb
<h1>Add a New Beverage</h1>
<p>Add your favorite beverage below, as many as you like.</p>

<%= render 'form' %>

<%= link_to 'Back', beverages_path %>

app/views/beverages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @beverage.name %>
</p>

<p>
  <strong>Kind:</strong>
  <%= @beverage.kind %>
</p>

<%= link_to 'Edit', edit_beverage_path(@beverage) %> |
<%= link_to 'Back', beverages_path %>

app/views/home/index.html.erb
<div class="row">
<h1>Home#Index</h1>
<p>This is the first page in the app!</p>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "BevyVote" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>

  <body>
  <div class="row">
   <%= render "shared/topnav" %>
    <%= yield %>
  </div>
  </body>
</html>

app/views/shared/_topnav.html.erb
<nav class="top-bar" data-topbar role="navigation">
  <ul class="title-area">
    <li class="name">
      <h1><a href="#">Bevy Vote</a></h1>
    </li>
     <!-- Remove the class "menu-icon" to get rid of menu icon. Take out "Menu" to just have icon alone -->
    <li class="toggle-topbar menu-icon"><a href="#"><span>Menu</span></a></li>
  </ul>

  <section class="top-bar-section">
    <!-- Right Nav Section -->
    <ul class="right">
      <li class="active"><a href="#">Sign Up</a></li>
    </ul>
</section>
</nav>

app/views/welcome/index.html.erb
<h1>Hello Rails!</h1>
<p>This is the first page in the app!</p>